name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python build_readme.py

      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull
          git add -A
          git commit -m "chore: update readme content" || exit 0
          git push
